### ISSUE TITLE
Canvas Student App for Flatiron pre-work course

### ISSUE THREAD

**Issue by EthanCKiss** [learn-co-curriculum/phase-0-navigating-canvas#1]
Hi,

I've just started my pre-work course for Flatiron and ran into my first problem. We're supposed to download the Canvas Student app to get through the course. But went I launched  the App store on my MacOS laptop, I couldn't find the Canvas Student app. When I googled it, the Apple Store says "This app is available only on the Apple Store for iPhone and iPad." See picture below. 

Is there a way to get this app for my laptop?  I don't think I can do the pre-work on my iPhone or iPad.

Thanks in advance!
Ethan

![IMG_6065](https://user-images.githubusercontent.com/93353126/141194537-15780a51-238a-4cef-9d61-77d41a71ba92.JPG)

**Comment by ihollander** [comment]
Hi @EthanCKiss, there's no need to download the app to work on the pre-work. All the assignments are available from the website at https://learning.flatironschool.com/. If you have questions or need support, please use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel. Good luck with the prework!

**Comment by EthanCKiss** [comment]
Thanks!
